---
apiVersion: postgresql.dev4devs.com/v1alpha1
kind: Database
metadata:
    name: library-database
spec:
    databaseCpu: 30m
    databaseCpuLimit: 60m
    databaseMemoryLimit: 512Mi
    databaseMemoryRequest: 128Mi
    databaseName: library_database
    databaseNameKeyEnvVar: POSTGRESQL_DATABASE
    databasePassword: book
    databasePasswordKeyEnvVar: POSTGRESQL_PASSWORD
    databaseStorageRequest: 1Gi
    databaseUser: book
    databaseUserKeyEnvVar: POSTGRESQL_USER
    image: centos/postgresql-96-centos7
    size: 1