INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'Sapiens' , 2011);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'Homo Deus' , 2015);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'Enlightenment Now' , 2018);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'Factfulness' , 2018);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'Sleepwalkers' , 2012);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'The Silk Roads' , 2015);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'The culture map' , 2016);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'Billy Summers' , 2021);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'The Handmaids Tale' , 2016);
INSERT INTO book(id, name, publicationYear) VALUES (nextval('hibernate_sequence'), 'The Institue' , 2019);
